create sequence USERS.USERS_SEQUENCE;
create table USERS.TOKEN(
    TOKEN_VALUE VARCHAR PRIMARY KEY NOT NULL,
    EXPIRATION_DATETIME DATE
);
create table USERS.AUTHORIZED_USER(
    ID INT PRIMARY KEY NOT NULL ,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    TELEPHONE VARCHAR,
    TOKEN_ID VARCHAR,
    FOREIGN KEY(TOKEN_ID) REFERENCES USERS.TOKEN(TOKEN_VALUE)
);
