create sequence USERS.USERS_SEQUENCE;
create sequence USERS.RESTAURANT_SEQUENCE;

create table USERS.TOKEN(
    TOKEN_VALUE VARCHAR PRIMARY KEY NOT NULL,
    EXPIRATION_DATETIME DATE NOT NULL
);

create table USERS.RESTAURANT(
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR NOT NULL
);

create table USERS.AUTHORIZED_USER(
    ID INT PRIMARY KEY NOT NULL ,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    TELEPHONE VARCHAR,
    TOKEN_ID VARCHAR,
    FOREIGN KEY(TOKEN_ID) REFERENCES USERS.TOKEN(TOKEN_VALUE)
);

create table USERS.EMPLOYEE(
    ID INT PRIMARY KEY NOT NULL ,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    TELEPHONE VARCHAR,
    TOKEN_ID VARCHAR,
    PASSWORD VARCHAR,
    RESTAURANT_ID INT,
    FOREIGN KEY(TOKEN_ID) REFERENCES USERS.TOKEN(TOKEN_VALUE)
);

create table USERS.MANAGER(
    ID INT PRIMARY KEY NOT NULL ,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    TELEPHONE VARCHAR,
    TOKEN_ID VARCHAR,
    PASSWORD VARCHAR,
    RESTAURANT_ID INT,
    FOREIGN KEY(TOKEN_ID) REFERENCES USERS.TOKEN(TOKEN_VALUE)
);
